pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'aspnet-core-webapi'       // Nom de l'image Docker
        DOCKER_TAG = 'latest'                     // Tag de l'image
        BUILD_CONFIGURATION = 'Release'          // Configuration du build (Release/Debug)
        DOTNET_PROJECT = 'AppTest/AppTest.csproj' // Chemin du fichier .csproj
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                git branch: 'master', url: 'https://github.com/Mohamed86122/Project-payment-gateway'
            }
        }

        stage('Restore Dependencies') {
            steps {
                echo 'Restoring dependencies...'
                sh 'dotnet restore ${DOTNET_PROJECT}'
            }
        }

        stage('Build Project') {
            steps {
                echo 'Building the project...'
                sh 'dotnet build ${DOTNET_PROJECT} -c ${BUILD_CONFIGURATION}'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                sh 'dotnet test ${DOTNET_PROJECT} -c ${BUILD_CONFIGURATION}'
            }
        }

        

    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
